var VITRINAS = [
  {
    n: 1,
    f: "mhb-vitrina1-soportes.html",
    t: {
      es: "Los soportes de la antigüedad",
      en: "The writing surfaces of antiquity",
      fr: "Les supports de l'Antiquité",
      de: "Die Schriftträger der Antike",
      it: "I supporti dell'antichità",
    },
  },
  {
    n: 2,
    f: "mhb-vitrina2-tanaj.html",
    t: {
      es: "El Tanaj y la tradición judía",
      en: "The Tanakh and the Jewish tradition",
      fr: "Le Tanakh et la tradition juive",
      de: "Der Tanach und die jüdische Überlieferung",
      it: "Il Tanak e la tradizione ebraica",
    },
  },
  {
    n: 3,
    f: "mhb-vitrina3-septuaginta.html",
    t: { es: "La Septuaginta", en: "The Septuagint", fr: "La Septante", de: "Die Septuaginta", it: "La Settanta" },
  },
  {
    n: 4,
    f: "mhb-vitrina4-peshitta.html",
    t: { es: "La Peshitta", en: "The Peshitta", fr: "La Peshitta", de: "Die Peschitta", it: "La Peshitta" },
  },
  {
    n: 5,
    f: "mhb-vitrina5-beato-de-liebana.html",
    t: {
      es: "El Beato de Liébana",
      en: "The Beatus of Liébana",
      fr: "Le Beatus de Liébana",
      de: "Der Beatus von Liébana",
      it: "Il Beato di Liébana",
    },
  },
  {
    n: 6,
    f: "mhb-vitrina6-biblia-de-san-luis.html",
    t: {
      es: "La Biblia de San Luis",
      en: "The Bible of Saint Louis",
      fr: "La Bible de Saint Louis",
      de: "Die Bibel des heiligen Ludwig",
      it: "La Bibbia di San Luigi",
    },
  },
  {
    n: 7,
    f: "mhb-vitrina7-biblia-de-napoles.html",
    t: {
      es: "La Biblia de Nápoles",
      en: "The Bible of Naples",
      fr: "La Bible de Naples",
      de: "Die Bibel von Neapel",
      it: "La Bibbia di Napoli",
    },
  },
  {
    n: 8,
    f: "mhb-vitrina8-biblia-de-gutenberg.html",
    t: {
      es: "La Biblia de Gutenberg y la Pauperum",
      en: "The Gutenberg Bible and the Pauperum",
      fr: "La Bible de Gutenberg et la Pauperum",
      de: "Die Gutenberg-Bibel und die Pauperum",
      it: "La Bibbia di Gutenberg e la Pauperum",
    },
  },
  {
    n: 9,
    f: "mhb-vitrina9-ana-de-bretana.html",
    t: {
      es: "Las Grandes Horas de Ana de Bretaña",
      en: "The Great Hours of Anne of Brittany",
      fr: "Les Grandes Heures d'Anne de Bretagne",
      de: "Die Grandes Heures der Anne de Bretagne",
      it: "Le Grandi Ore di Anna di Bretagna",
    },
  },
  {
    n: 10,
    f: "mhb-vitrina10-poliglota-complutense.html",
    t: {
      es: "La Biblia Políglota Complutense",
      en: "The Complutensian Polyglot Bible",
      fr: "La Bible polyglotte d'Alcalá",
      de: "Die Complutensische Polyglotte",
      it: "La Bibbia Poliglotta Complutense",
    },
  },
  {
    n: 11,
    f: "mhb-vitrina11-textus-receptus.html",
    t: {
      es: "El Nuevo Testamento de Erasmo",
      en: "The New Testament of Erasmus",
      fr: "Le Nouveau Testament d'Érasme",
      de: "Das Neue Testament des Erasmus",
      it: "Il Nuovo Testamento di Erasmo",
    },
  },
  {
    n: 12,
    f: "mhb-vitrina12-biblia-de-lutero.html",
    t: {
      es: "La Biblia de Lutero",
      en: "Luther's Bible",
      fr: "La Bible de Luther",
      de: "Die Lutherbibel",
      it: "La Bibbia di Lutero",
    },
  },
  {
    n: 13,
    f: "mhb-vitrina13-english-hexapla.html",
    t: {
      es: "La English Hexapla",
      en: "The English Hexapla",
      fr: "L'English Hexapla",
      de: "Die English Hexapla",
      it: "L'English Hexapla",
    },
  },
  {
    n: 14,
    f: "mhb-vitrina14-vita-christi.html",
    t: {
      es: "El Vita Christi de Montesino",
      en: "Montesino's Vita Christi",
      fr: "La Vita Christi de Montesino",
      de: "Die Vita Christi des Montesino",
      it: "La Vita Christi di Montesino",
    },
  },
  {
    n: 15,
    f: "mhb-vitrina15-enzinas.html",
    t: {
      es: "El Nuevo Testamento de Enzinas",
      en: "The New Testament of Enzinas",
      fr: "Le Nouveau Testament d'Enzinas",
      de: "Das Neue Testament des Enzinas",
      it: "Il Nuovo Testamento di Enzinas",
    },
  },
  {
    n: 16,
    f: "mhb-vitrina16-biblia-de-ferrara.html",
    t: {
      es: "La Biblia de Ferrara",
      en: "The Ferrara Bible",
      fr: "La Bible de Ferrare",
      de: "Die Ferrara-Bibel",
      it: "La Bibbia di Ferrara",
    },
  },
  {
    n: 17,
    f: "mhb-vitrina17-perez-de-pineda.html",
    t: {
      es: "El Nuevo Testamento de Pérez de Pineda",
      en: "The New Testament of Pérez de Pineda",
      fr: "Le Nouveau Testament de Pérez de Pineda",
      de: "Das Neue Testament des Pérez de Pineda",
      it: "Il Nuovo Testamento di Pérez de Pineda",
    },
  },
  {
    n: 18,
    f: "mhb-vitrina18-biblia-del-oso.html",
    t: {
      es: "La Biblia del Oso",
      en: "The Bear Bible",
      fr: "La Bible de l'Ours",
      de: "Die Bärenbibel",
      it: "La Bibbia dell'Orso",
    },
  },
  {
    n: 19,
    f: "mhb-vitrina19-biblia-del-cantaro.html",
    t: {
      es: "La Biblia del Cántaro",
      en: "The Pitcher Bible",
      fr: "La Bible de la Cruche",
      de: "Die Krugbibel",
      it: "La Bibbia della Brocca",
    },
  },
  {
    n: 20,
    f: "mhb-vitrina20-biblia-de-scio.html",
    t: {
      es: "La Biblia del Padre Scío",
      en: "Father Scío's Bible",
      fr: "La Bible du Père Scío",
      de: "Die Bibel des Pater Scío",
      it: "La Bibbia di padre Scío",
    },
  },
  {
    n: 21,
    f: "mhb-vitrina21-torres-amat.html",
    t: {
      es: "La Biblia de Torres Amat",
      en: "The Torres Amat Bible",
      fr: "La Bible de Torres Amat",
      de: "Die Torres-Amat-Bibel",
      it: "La Bibbia di Torres Amat",
    },
  },
  {
    n: 22,
    f: "mhb-vitrina22-vence-de-galvan.html",
    t: {
      es: "La Biblia de Vence, de Galván",
      en: "Galván's Vence Bible",
      fr: "La Bible de Vence, de Galván",
      de: "Die Vence-Bibel von Galván",
      it: "La Bibbia di Vence, di Galván",
    },
  },
  {
    n: 23,
    f: "mhb-vitrina23-grabados.html",
    t: {
      es: "Los grabados: Schnorr y Doré",
      en: "The engravings: Schnorr and Doré",
      fr: "Les gravures : Schnorr et Doré",
      de: "Die Stiche: Schnorr und Doré",
      it: "Le incisioni: Schnorr e Doré",
    },
  },
  {
    n: 24,
    f: "mhb-vitrina24-siglo-xx.html",
    t: {
      es: "Las seis del siglo veinte",
      en: "The six of the twentieth century",
      fr: "Les six du vingtième siècle",
      de: "Die sechs des zwanzigsten Jahrhunderts",
      it: "Le sei del Novecento",
    },
  },
  {
    n: 25,
    f: "mhb-vitrina25-biblia-de-dali.html",
    t: {
      es: "La Biblia de Dalí",
      en: "Dalí's Bible",
      fr: "La Bible de Dalí",
      de: "Die Bibel von Dalí",
      it: "La Bibbia di Dalí",
    },
  },
  {
    n: 26,
    f: "mhb-vitrina26-biblias-de-hoy.html",
    t: {
      es: "Las Biblias de hoy",
      en: "The Bibles of today",
      fr: "Les Bibles d'aujourd'hui",
      de: "Die Bibeln von heute",
      it: "Le Bibbie di oggi",
    },
  },
  {
    n: 27,
    f: "mhb-vitrina27-braille.html",
    t: {
      es: "La Biblia en Braille",
      en: "The Bible in Braille",
      fr: "La Bible en braille",
      de: "Die Bibel in Blindenschrift",
      it: "La Bibbia in braille",
    },
  },
  {
    n: 28,
    f: "mhb-vitrina28-lenguas-de-mexico.html",
    t: {
      es: "Las lenguas de México",
      en: "The languages of Mexico",
      fr: "Les langues du Mexique",
      de: "Die Sprachen Mexikos",
      it: "Le lingue del Messico",
    },
  },
  {
    n: 29,
    f: "mhb-vitrina29-lenguas-del-mundo.html",
    t: {
      es: "Las lenguas del mundo",
      en: "The languages of the world",
      fr: "Les langues du monde",
      de: "Die Sprachen der Welt",
      it: "Le lingue del mondo",
    },
  },
  {
    n: 30,
    f: "mhb-vitrina30-biblias-miniatura.html",
    t: {
      es: "Las Biblias miniatura",
      en: "The miniature Bibles",
      fr: "Les Bibles miniatures",
      de: "Die Miniaturbibeln",
      it: "Le Bibbie in miniatura",
    },
  },
  {
    n: 31,
    f: "mhb-vitrina31-seccion-infantil.html",
    t: {
      es: "La sección infantil",
      en: "The children's section",
      fr: "La section enfants",
      de: "Die Kinderabteilung",
      it: "La sezione per bambini",
    },
  },
  {
    n: 32,
    f: "mhb-vitrina32-version-apa.html",
    t: {
      es: "La versión APA",
      en: "The APA version",
      fr: "La version APA",
      de: "Die APA-Fassung",
      it: "La versione APA",
    },
  },
];
